
version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
    ports:
      - '80:80'
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
